### ISSUE TITLE
Possible to drag freeform poly?

### ISSUE THREAD

**Issue by cmlnrowan** [robidev/Leaflet.Draw.Svg#1]
Looks amazing so far.  Kudos on achieving accessible sophistication.  I noticed that a freeform poly doesn't display a drag node in edit mode like circles and squares.  Any way to enable that?

**Comment by robidev** [comment]
Hi, thanks. However, my part is only a small addition to Leaflet.Draw; namely the possibility to load/edit svg images. The drawing/editing of polylines, polygon, square and circle are part of the main Leaflet.Draw. Therefore I think main credit, but also this issue is related to that library. My code does not contain anything specific regarding the polyline/polygon. Therefore I will close this issue, as I cannot fix it. I suggest you open the issue in Leaflet.Draw instead here https://github.com/Leaflet/Leaflet.draw
